# Generated by Django 3.1.2 on 2020-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('neutured', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=1, null=True)),
                ('image', models.CharField(default='photo.jpg', max_length=200)),
            ],
        ),
    ]
