# Generated by Django 3.1.2 on 2020-10-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201029_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='shelterName',
        ),
    ]
