# Generated by Django 3.1.2 on 2020-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201029_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
